AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template ACE-MSP-Ansible Tower-VMs-v1: A Template for
  provisioning the Ansible VMs for the MSP Stack used in the ACE ITOM End To
  End Demo. **WARNING** This template creates 1 Amazon EC2 instance and requires an existing EIP. You will
  be billed for the AWS resources used if you create a stack from this template.
Resources:
  AnsibleTower:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.small
      ImageId: !Ref TOWERAMI
      SubnetId: !Ref SubNet
      SecurityGroupIds:
        - !Ref SecGroup
      KeyName: ACE-Linux-SSH
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - ACN-MSP-TOWER-
              - !Ref LABCODE
        - Key: OSType
          Value: Linux
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 96ddedfe-6e9f-425f-bf4b-9849f8b29032
  EIPAllocation:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      AllocationId: !Ref EIPID
      InstanceId: !Ref AnsibleTower
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 64526e66-f1c9-4d7e-9b45-8c0fbee8645d
Parameters:
  LABCODE:
    Description: Users LAB Code
    Type: String
  SubNet:
    Description: VPC Subnet
    Type: String
    Default: subnet-0fafceb72d2a5c41e
  SecGroup:
    Description: Security Group
    Type: String
    Default: sg-0d93dcf2e42ac18a8
  TOWERAMI:
    Description: Ansible Tower AMI
    Type: String
    Default: ami-0c7cad8a2a005a721
  EIPID:
    Description: Elastic IP Allocation ID
    Type: String
    Default: eipalloc-04e73fdf70e56f8d8
